export const constants = {
    wentWrong: "Something went wrong. Try again later",
    emailNotFound: "User with this email not found",
    wrongPassword: "Wrong password",
    wrongEmail: "Check entered email",
    emailInUse: "Email has already been taken",
    authUserNotFound: "auth/user-not-found",
    authWrongPassword: "auth/wrong-password",
    authEmailInuse: "auth/email-already-in-use",
    authWrongEmail: "auth/invalid-email",
    recoveryPassword: "Password recovery instructions was sent to the email address",
    reset: "Reset",
    register: "Register",
    signIn: "Sign In",
    forgotPassword: "Forgot password",
    passwordRecovery: "Password Recovery",
    daysName: ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"],
    monthsName: ["jan", "feb", "mar", "apr", "may", "june", "july", "aug", "sep", "oct", "nov", "dec"],
    addNewTask: "Add new task",
    taskPlanned: "tasks planned",
    noTasks: "No tasks planned",
    delete: "Delete",
    cancel: "Cancel",
    save: "Save",
    edit: "Edit"

}